### ISSUE TITLE
Feature request: Server option to limit # of connections from same player

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1024]
Hi, it would be useful to have an option in the server config to be able to define how many clients are able to connect from one IP address.

**Comment by compomega** [comment]
Discrimination based on IP address is not a good idea. There can be multiple people wanting to play that share the same IP address because they are in the same home, on the same school/corporate network or even just happen to be coming from the same ISP. While this might prevent multi-clienting (or whatever else you may be trying to prevent) it would also prevent legitimate play from those in the aforementioned situations. Perhaps it is better to prevent or deter this behavior in a different way.

Also, if there is some group or region DDoSing or generally being trolls that should be addressed at a lower level of the network stack before the communication hits any of your services.

**Comment by alkalime** [comment]
What about MAC address, since that's more specific?

**Comment by compomega** [comment]
No, the MAC address is not available at the application layer. Even if it was it would probably not be the MAC of the actual client but of some router or other hop between you and the client.

**Comment by compomega** [comment]
If the intention is to limit the number of clients run by the same player we have a proposal that should not block legitimate play. Let us know if that's what you're looking for and we can update the description/title of the issue.

**Comment by alkalime** [comment]
That's exactly what I'm looking for, yeah
