### ISSUE TITLE
Mitama Bonus for Magnetite summon cost reduction is nonfunctional

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#1043]
While the reunion bonus from the Ingwaz path correctly reduces the amount of magnetite needed to summon a demon, the mitama bonus that should reduce magnetite cost does not work; two copies of the same demon that are the same level will have the same magnetite cost whether or not one of them has the mitama bonus.

**Comment by HACKfrost** [comment]
Delaying this for next release because of how the calculation is currently handled. The real problem arises when including the player skill that boosts the reduction further. The player learning/forgetting the skill or lowering their expertise below the required level to passively forget the skill could potentially require the comp be resent to the client which is larger than a small bug in my opinion.
