### ISSUE TITLE
Attack Animation Bug with Melee Skills from TMG (False)

### ISSUE THREAD

**Issue by TheRealHitoshura** [comphack/comp_hack#1162]
The melee skills effects from TMG (False) are not aligning with the attack animation for the skill. In my test, I choose Blizzard Attack and Blizzard Spread. I alternate between the TMG skills and Armor break to show the visual difference in speed. However, these skills are simply Attack skills (No Incant/CD), so they should coincide with the speed of other Attack skills that are already working correctly.

https://streamable.com/gcnna

Attached are also some pictures of the skill reference data for The TMG skills and Attack skills for the Incant/CD (Which is 0).

***There is only an issue with the attack effect being in sync with the animation. The modifier is fine.
![ABReference](https://user-images.githubusercontent.com/49658543/76684139-cecee780-65df-11ea-8023-f54e6a0508a8.PNG)
![blizzattack](https://user-images.githubusercontent.com/49658543/76684140-cf677e00-65df-11ea-9562-0ba471e3aa8c.PNG)
![blizzspread](https://user-images.githubusercontent.com/49658543/76684141-cf677e00-65df-11ea-84d8-6e0db9726137.PNG)

**Comment by HACKfrost** [comment]
Those are projectiles with a speed identical to corona attack. Does it differ from that skill for you?

**Comment by TheRealHitoshura** [comment]
Projectiles? No, they're all attacks. The only comparable thing to Spread skills is the AOE Attack Book from Invasion, which also works fine. I think that all of the TMG skills are affected by this. The video event shows that the skills come out like 3 seconds later or 1 second after being cast; there's tons of inconsistency, like counter triggering way later, that was shown by the skills in the video.

**Comment by HACKfrost** [comment]
The skill data has a projectile speed for the blizzard skills that is identical to that skill. Please compare it to corona attack.

**Comment by carlosrijo** [comment]
Hi!

I found an old footage where we can see those attack in action.
I've uploaded it on youtube: https://youtu.be/G5PvWwhyXhk?t=990
Please watch it until the 22:30min mark.

I analyse some demons between the 16:30 and 22:30min time window. Specifically Hecate and Michael.
Hecate has the Hurricane Spread. Michael has the Corona and Blizzard Spread.
There are a lot of times where you can clearly see them using those attacks and the animation is the same as the normal attack animation (or at least very close to).

I've also used those skills a lot later when I got better. Unfortunately I don't have footage of said times...but I can tell that the animation was really, really close (if not the same) as the normal attack.

I hope this helps.

**Comment by HACKfrost** [comment]
Thank you. This is definitely useful but here is the problem (and I apologize in advance for the info dump). If I use this skill on reimagine where this is being tested, I don't have the delay being shown in the original videos because projectile or no, you have to use it at the lowest max distance (300 units for a "small hitbox" target) which gives it the minimum delay of a single server tick, approximately 1/10th of a second after usage (unless there is currently a lot of strain on the server). These skills all have a target range of +0 which is what enforces that max distance mentioned. I can see this working a couple ways:

1) Projectile speed is ignored due to +0 target range. The only skills configured this way could easily be interpreted as "never cleaned up" by the original developers from some idea they had a while back. Demon summoning, demon storing (in comp) and (the act of) digitalize canceling all have data like this and its obvious those three gain absolutely nothing from a projectile since they don't even target another entity.

2) Projectile speed is ignored because it is an attack action type. Up to this point the number of things that could not be explained for any reason other than action type has been very, very minimal. Defensive to attack skills are an explicit interaction established by in game text and developer postings. Guard has the additional trait of damage reduction based on its skill modifier. Rush has the added "rush time" which implicitly makes it slow enough to be hit cancelled by attack. However rush can also fail to hit cancel from attack and can occasionally be hit cancelled by spin if the timing is just right, both things we replicated multiple times on the live servers. The "on hit" behavior of defensive skills is actually an activation type field as well. Long story short, action type is typically something that has shared traits, not the rule. If it overrode projectile logic here, what do you infer about hypothetical spins with projectile speeds set?

3) Projectile speed is ignored because you can't see the projectile. This one is a big "maybe" to me but can be proven by the few skills that are shots with invisible projectiles having any delay at all. It would be strange if this was the first instance where the logic from the definition file is overridden by the logic of the client file which is typically in charge of stuff like names, visual effects etc.

4) The projectile speed is NOT ignored and the connection of the player is the main difference in speed. This one is the current state and is obviously hard to prove to in fact be true. You can however compare it to other skills to see if it matches that behavior at least. You can stand at the same distance from an enemy and use a visible projectile skill to see if it has the same timing. You can put a projectile on the skill in its client definition and see if it visually looks correct. Keep in mind that while we did reference old packet recordings to get the timing down, the ultimate deciding factor on the actual timing precision was how it visually looked when it "made contact" with the target. I would say you can try the skill local or with a more solid connection to the server but I already did that and we can't really prove that the recordings on the original servers had fast connections or not.

**Comment by Fizzlybub** [comment]
https://youtu.be/gUDfZbwuaBE?t=16

In this video, you can see a difference in how quickly the damage appears depending on the distance kumbhanda is from the enemy based on where he is in his attack animation.

**Comment by carlosrijo** [comment]
I leave here a few videos of the _at the time of writing_ behavior:
https://streamable.com/ggqig
https://streamable.com/vewfi
https://streamable.com/f08sc
https://streamable.com/1r8bq
