### ISSUE TITLE
Cave of life Movement passives

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#1171]
I noticed a few of these passives are not working or maybe not stacking?
![cxvxcvcxvcvxcxv](https://user-images.githubusercontent.com/48490613/77703910-ac06e080-6f9a-11ea-96a6-06b904477ef7.JPG)
i tried to hit the movement cap (50%) using different sources and the skills. But people with an orb of speed still run faster than me.
i dont know which ones are not working but im pretty sure only the first one does work because i tested them in order from 1 to 5 and i was able to outrun my demon but only by a little bit by having only the first one.

Steps to Reproduce:
1- Go to cave of life
2- Buy the passives using Orbs of hope (ID: 12988)
3- Hit the movement cap using this back ID:35677
4- Compare your Speed with something that has an orb of speed

Note: I was not able to find the skills ID

**Comment by HACKfrost** [comment]
The back item is +30%, the five passives (starting at 50020) are all +4% each and do stack. This would put you at +50% as you stated.

The fact that these are percentage adjustments is the problem because of how our max speed detection logic works. Numeric adjustments (which most are for speed) and full 50% adjustments are unaffected by this. Good find!
