### ISSUE TITLE
Demon Spawning CMD

### ISSUE THREAD

**Issue by Rayerra** [comphack/comp_hack#1255]
Hey i would like to have a addition feature when you use the @enemy CMD since it only spawns 1 of the selected MOB
Id like to have a CMD like @Enemy ID Number
The number dictates how many is spawned

At the end of the NA server the last few hours the GM's was able to spawn a mass number of a selected demon.
I think this would be more covenant to GM's or PPL in power that has the @Enemy cmd permission Lv. to host spawn events without having to spam the single cmd 1 at a time

**Comment by TallgeeseHeaven** [comment]
I would think you could write a script using Squirrel for that, no?

**Comment by compomega** [comment]
Such a command would spawn at the location of the GM instead of randomly across a designated area. Such an event has not worked well in the past. The GM command is meant more for testing than for events. You could create an event that spawns enemies and use @event to trigger it. Do you need help making the content XML to do this? Can we close this issue?
