### ISSUE TITLE
Pentalfa got the wrong winners

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#1281]
last week indra won even though the bar was filled to the left while kresnik that bar was filled to the right got 5th place

also to notice people that are not placed in first place do not gain any coins

**Comment by TallgeeseHeaven** [comment]
![pent_lastweek_ranks](https://user-images.githubusercontent.com/4992450/99587400-0c79e080-29b7-11eb-834d-a4cafd6adb5b.png)
![pent_lastweek_bars](https://user-images.githubusercontent.com/4992450/99587401-0c79e080-29b7-11eb-96a5-082b1986197b.png)

Here are the relevant images. They do not seem exactly reversed, because if they were Kresnik would be 4th...

**Comment by TallgeeseHeaven** [comment]
@alkalime 

Is the server option to not pay out people in second place and below set?

**Comment by Rayerra** [comment]
for the longest i haven't had it on mine but last restart i added it i didn't know this was in documentation till it was brought up

**Comment by TallgeeseHeaven** [comment]
@alkalime 

If you could get the Rankings blob for last week's match under PentalphaMatch, that would help in this. Please do so if you can.

**Comment by Gricros** [comment]
that print wasnt on final day
in the end kresnik got first place
