### ISSUE TITLE
Crash with unhandled exception

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1400]
This crash has been happening for the past few weeks and the channel log doesn't log any information besides the unhandled exception. It seems to be related to moving a demon in the depo somehow? 

`[2021/05/25 15:33:19] CRITICAL: The server has crashed with an unhandled exception. A backtrace will follow.
[2021/05/25 15:33:19] CRITICAL: Backtrace: comp_channel(objects::Demon::GetBoxSlot+0x0) c:\build-outside\libcomp\libcomp\objgen\demon.cpp:3164
comp_channel(channel::Parsers::DemonBoxMove::Parse+0x334) d:\a\comp_hack\comp_hack\server\channel\src\packets\game\demonboxmove.cpp:79
comp_channel(libcomp::ManagerPacket::ProcessMessage+0x340) d:\a\comp_hack\comp_hack\libcomp\libcomp\src\managerpacket.cpp:94
comp_channel(libcomp::Worker::HandleMessage+0x328) d:\a\comp_hack\comp_hack\libcomp\libcomp\src\worker.cpp:129
comp_channel(libcomp::Worker::Run+0x21d) d:\a\comp_hack\comp_hack\libcomp\libcomp\src\worker.cpp:86
comp_channel(std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_f0923ea92f8b4eee81a34e73b6976b1e>,std::shared_ptr<libcomp::MessageQueue<libcomp::Message::Message *> >,libcomp::String>,std::default_delete<std::tuple<<lambda_f0923ea92f8b4eee81a34e73b6976b1e>,std::shared+0xa4) c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread:230
comp_channel(std::_Pad::_Call_func+0x9) c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\thr\xthread:209
(_o__realloc_base+0x60)
(BaseThreadInitThunk+0x14)
(RtlUserThreadStart+0x21)`

**Comment by TallgeeseHeaven** [comment]
This crash is only possible with invalid demon information, implying that you have directly edited the database in some manner.

What happened here exactly?

**Comment by TallgeeseHeaven** [comment]
Well, did you all change something about DevilData?

**Comment by s4trace** [comment]
Yeah there are custom entries in DevilData however they do not cause a crash when contracted, spawned or stored in the depo nor are there any IDs in the database that do not exist in DevilData. It would be nice to handle the exception for this case to at least print out what caused the error in the server's logs.

**Comment by TallgeeseHeaven** [comment]
Did you edit the database at all?

**Comment by Rekuiemu** [comment]
If you did make a SQL database edit best practice is to do a backup or a dump before making any changes
Data Management 101, i say this so you can have something to fall back on if you did screw anything up.

Even i screwed up my database but a simple rollback before i made the changes fixed the issue and i was able to make rightful adjustments to make the corrections of what i changed in the servers sbins edits to reflect each other without conflicts.

A Quote from Omega himself.
DON'T ever edit your database.

He only says that because it holds major risks if you don't know what your doing.

Anyways i could help if i knew exactly what you changed but not sure if you want to share that info.

**Comment by s4trace** [comment]
> Did you edit the database at all?
> 
> What started this, exactly?

I haven't edited the database and I can't seem to replicate the crash with any demon myself which is why I opened this issue. It would be a great addition to the server software if we had some sort of exception handling or if it at least printed whatever caused the crash in the first place.

**Comment by Fizzlybub** [comment]
Steps to replicate:
@contract 21
@contract 270
Go into the Demon Table of the World database, change the type of Metatron (21) to 20 and save the database.
Relog on same character, enter demon depository.
Move Kodama into the slot Metatron was previously in.
Kodama will appear in both slots.
Leave demon depository.
Summon Kodama to identify Kodama's actual slot.
Toss actual Kodama.
Move Metadama into a different slot.

**Comment by TallgeeseHeaven** [comment]
Uh huh.

So what I'm seeing here is that I have been lied to.

**Comment by HACKfrost** [comment]
I'm fairly confident that Fizzy found a similar issue that is not the same. I shared a migration script that would identify any demons double registered in a player's boxes and it found 0 upon scanning every account. I also verified that a dump of demon types only showed outliers that are defined in their custom binary data. It's not IMPOSSIBLE that the proposed offending player has a mismatch in their DevilData file and the client just barfs if this happens but I am just speculating. At this point I'm not sure what to suggest apart from trying to find out who was on when the servers went down but that's a bit tricky to pin down based on the player count.

The fix for this instance is one that should be there either way. It's just a null check I missed in the DemonBoxMove parser. Log it, kick em and move on like usual.

Anyway I suggest less snark if you want to continue supporting player engagement in reporting bugs. From what I can see here the person who reported it doesn't even have access to the information you asked. Please play nice kids.

**Comment by TallgeeseHeaven** [comment]
I support player engagement of people who accurately and fully report the issue and what they may have done to cause it. If they decide to hide something for whatever reason it seems appropriate to point it out.
