### ISSUE TITLE
Consumables used twice on activation

### ISSUE THREAD

**Issue by Aileidia** [comphack/comp_hack#148]
# Steps to Reproduce

Use a non-targeted AoE consumable

# Expected Behavior

The item should be used once

# Actual Behavior

The item is used twice in succession before going on cooldown

**Comment by HACKfrost** [comment]
This should probably be paired with combat skills in Pixie Phase 3 because the core issue requires identification of identifying skills with zero charge time that should execute immediately or wait for the callback from the client.  For example basic healing items need to wait for the callback from the client (hence the double cast) but the basic physical attack should not.  The latter group of skills also appear to not send a packet stating that the skill has completed while the former does.
