### ISSUE TITLE
Demon Depository Crash

### ISSUE THREAD

**Issue by deletion123** [comphack/comp_hack#285]
When moving a demon into the depo, it crashes the game but upon logging back in the demon is moved into the depo. After the relog if I move the demon back into my COMP it moves the demon but the picture of the demon I moved stays in the depository if I click on the picture then I d/c from the server.

> essentially the client is being told there is no demon there and the server tells it to move it
> so it crashes
> the data packet saying what we did is the problem though, please include this in the bug

**Comment by ApexPie** [comment]
Your experience differs slightly from mine; main difference being that my client doesn't crash putting the demon(s) in.
Placing demon(s) in depository causes them to disappear. Relogging makes the demon(s) reappear, but removing the demon(s) from depository initiates a server disconnect. Everything seems to be alright after logging in after the disconnect.

**Comment by compomega** [comment]
I was able to reproduce what @ApexPie said. It produced the following error (server side) which led to the disconnect:
ERROR: Invalid arguments supplied for demon move request 1, 14, 0, 0

The demon was still not visible even when talking to the NPC a second time prior to logging out.

@deletion123 A crash of the client means windows says the application encountered an error. A disconnect results in the red error message (usually in Japanese) but the client still functions. The distinction can be important as the former could indicate a bad packet causing the client to do something unexpected and the latter usually indicates the server encountered something it didn't like.

**Comment by compomega** [comment]
After the bugged demon is placed back in the COMP you can no longer contract demons because the server crashes:
`CRITICAL: The server has crashed. A backtrace will follow.
CRITICAL: Backtrace: bin/comp_channel() [0x8a84d6]
CRITICAL: Backtrace: /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f80de3714b0]
CRITICAL: Backtrace: bin/comp_channel(_ZNK7libcomp16PersistentObject7GetUUIDEv+0) [0x8b8b90]
CRITICAL: Backtrace: bin/comp_channel(channel::CharacterManager::ContractDemon(std::shared_ptr<channel::ChannelClientConnection> const&, std::shared_ptr<objects::MiDevilData> const&, int)+0xa4) [0x6fc524]
CRITICAL: Backtrace: bin/comp_channel(channel::ChatManager::GMCommand_Contract(std::shared_ptr<channel::ChannelClientConnection> const&, std::__cxx11::list<libcomp::String, std::allocator<libcomp::String> > const&)+0x10d) [0x70608d]
CRITICAL: Backtrace: bin/comp_channel(channel::ChatManager::ExecuteGMCommand(std::shared_ptr<channel::ChannelClientConnection> const&, libcomp::String const&, std::__cxx11::list<libcomp::String, std::allocator<libcomp::String> > const&)+0x152) [0x7011d2]
CRITICAL: Backtrace: bin/comp_channel() [0x76a3fc]
CRITICAL: Backtrace: bin/comp_channel(libcomp::Message::ExecuteImpl<channel::ChatManager*, std::shared_ptr<channel::ChannelClientConnection>&, libcomp::String&, std::__cxx11::list<libcomp::String, std::allocator<libcomp::String> >&>::Run()+0x3c) [0x76b91c]
CRITICAL: Backtrace: bin/comp_channel(libcomp::Worker::Run(libcomp::MessageQueue<libcomp::Message::Message*>*)+0x690) [0x8ed0e0]
CRITICAL: Backtrace: bin/comp_channel() [0x8ed129]
CRITICAL: Backtrace: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f80decddc80]
CRITICAL: Backtrace: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f80df1b26ba]
CRITICAL: Backtrace: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f80de4433dd]`

**Comment by compomega** [comment]
Actually this was because I was summoning a demon with an ID that didn't exist (miss-read another bug). I'll fix that crash.
