### ISSUE TITLE
HP/MP boosts not persisting

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#442]
Flat boosts to a player's HP/MP should persist (gear, expertise passives, etc).  Upon leveling up or zoning, stats are completely recalculated and all bonuses are lost.

**Comment by Fizzlybub** [comment]
Steps to replicate:
1. Use skill gmand to add a passive that modifies HP/MP (2 or 50000)
2. Use levelup gmand to gain a level.

Expected behavior:
If the player is alive, HP/MP are recalculated including the passives, then filled to maximum.

Observed behavior:
The passives are not included in the calculation of the new HP/MP totals.
