### ISSUE TITLE
Daily Mission

### ISSUE THREAD

**Issue by compomega** [comphack/comp_hack#716]

**Comment by nakano15** [comment]
The Daily Missions are being given on the wrong day. Based on [Sesshou wiki](http://megaten.sesshou.com/wiki/index.php/Daily_Mission), the server is giving me tomorrow's daily mission.
Today is Friday, but the server is giving Shibuya Quartz (Bronze) which is Saturday's level 1 mission.

That may or may not be a bug, since I have is no idea of where the server is being hosted. If the server is on the other side of the world compared to my position, then there is no bug at all.

**Comment by compomega** [comment]
Please do not necro an old closed issue for a new question or bug. It's Saturday morning in Japan right now which is the default time configuration for the server. See the TimeOffset option in the [World Shared Configuration](https://comphack.github.io/comp_hack/guide/ch02s06.html#idp47376757585248) of the guide for more information.

**Comment by nakano15** [comment]
Sorry, I was going to create a new issue post for this, but after reading the Posting Issues post saying to search first for an existing issue before posting, I thought that was to post here (I rarelly use Github, though).

And I kind of thought about the possibility that the server might be hosted in japan, but had no idea on how to find about that (even more since I don't use discord).

By the way, double sorry for this. :/

**Comment by compomega** [comment]
Thank you for pointing that out. I should probably clarify in the pinned issue that we want users to search for existing issues that describe their problem or request. If you can't find one that mentions your issue you should make a new one.
