### ISSUE TITLE
Earth Mother racial gifts are broken.

### ISSUE THREAD

**Issue by 2seoTH** [comphack/comp_hack#875]
By using "Care" or "Mooch" on a demon with high friendship level you can receive an item. Items are determined by race and each race has their own R8 relic item. However, several Earth Mother demons are giving wrong items or not giving anything at all.

Reproducing "wrong items": 
1.Get any of the following demons:
Kikuri-Hime, Kushinada-Hime, Parvati, Skadi.
2.Raise friendship level to Open Hearts of above.
3.Use "care" on them until you get relic item.
Expected: 盤古の卵(pangu seed)
Actual: 神託鏡(oracle mirror)

Reproducing "no gifts":
1.Get any of the following demons:
Diana, Ishtar
2.Raise friendship level to Open Hearts of above.
3.Use "care" on them
Expected: Item gift
Actual: Nothing happens

**Comment by HACKfrost** [comment]
This is all content based. The list was based off the CN server rewards as there are not recordings of the updated rewards anywhere. If you want to go through and flesh out the list, you are likely at least as qualified to do so as anyone else. The "full list" is lost to time either way.

**Comment by Beat4** [comment]
Where can i find the List? i know about a few items that are currently missing from the Care Rewards.

**Comment by HACKfrost** [comment]
Our file is in data/demonpresent.xml in the server files. The IDs will match the races here:
https://github.com/comphack/libcomp/blob/develop/libcomp/schema/binarydata/devildata.xml

**Comment by HACKfrost** [comment]
After finally looking into this, there is nothing specific to Earth Mother about what is being reported. All 4 of the mentioned demons have both of those items in the "rare" category, Isis however (an example from the same family) only has the one you expected. It's not as simple as what is on [fc2's page](http://megatenonline.wiki.fc2.com/wiki/%E4%BB%B2%E9%AD%94%E3%81%8B%E3%82%89%E3%81%AE%E3%83%97%E3%83%AC%E3%82%BC%E3%83%B3%E3%83%88) but it also appears that they did not change these between CN and JP except for adding more options like the DCMs, talismans and melons. Of all non-base demons mapped in the current file, 43 out of 450 have a difference between the explicit type and the base type that is not the base type just having additional items in the set (not sure why that difference was so common as it seems backwards). Since the base demon and the derived types are so similar, the remaining 64 base types (minus like 25 or so that aren't "real" demons) should be pretty easy to infer and the derived types should be something we can build based off those.

That all being said, fc2's page is a pretty good resource for building this but considering the items listed as things that were unverified or even false are part of the file we have, its clear no one _ACTUALLY_ knows the complete set anymore. I say we keep the anomalies, play it safe for anything not there and merge in the newly added items from fc2 to complete this list.

**Comment by HACKfrost** [comment]
Fixed for Eihwaz. I removed everything in the 出なくなったアイテム sections on the fc2 page, downgraded everything in their middle "Rare" 現在不明な物 section to our middle "Uncommon" section, regenerated all the mapped items on the page, kept all the unique entries not on the page at all (there aren't many) and added a very rare item one player could prove existed that's not on this page or our CN file.
