### ISSUE TITLE
Received Curative effects % is not affecting Consumables (items)

### ISSUE THREAD

**Issue by Beat4** [comphack/comp_hack#883]
The angel im using has some of the Saien demon force items that gives % "Curative recieved" to User, they should affect items used on me. (they work fine with healing abilities such as Dia/Media etc)
![Captureeee](https://user-images.githubusercontent.com/48490613/54417268-6ef9e400-46e0-11e9-8d65-0a1bf74fbb57.JPG)

Steps:
1. Buy the Demon Force items in the picture from Saien
2. put them on your demon
3. Try to use healing items like Oitments

**Comment by HACKfrost** [comment]
Currently we're having an internal discussion about if this missing part of the calculations affects the following on both static and percent healing/damage skills:
-Correct Table (stat) RATE and RATE_TAKEN of CLSR, LNGR, support, spell and healing
-Correct Table player/demon RATE and RATE_TAKEN
-Tokusei EFFECT_POWER (healing or damage, ex: アタックの威力＋５％)
-Tokusei DAMAGE_DEALT (damage only, ex: 大種族・人間へのダメージ＋３％)
-Tokusei DAMAGE_TAKEN (damage only, ex: 大種族・人間からのダメージ－１％)

I'm not a lot of help here so we'll need some examples to decide which are most accurate.

**Comment by HACKfrost** [comment]
So our conclusive findings are as follows:
-static heal rate: Y (recording of chakra crepe, likely applies during drain from target in error)
-static dmg rate: Y (seth does 300 with 100 skill against demons)
-percent heal rate: ?
-percent dmg rate: Y (recording against hitosura max percent skill)
-static/percent dmg/heal tokusei "effect": ?
-static/percent dmg/heal tokusei rate: ?

We checked a lot of skills both in our recordings and online and I think we may simply not have these types of examples visible to us. That being said we can make some assumptions and take action on what we do have.

1. Percent heal is likely also affected by rate adjustments. I see no reason to believe its special just because its healing when the static heal/dmg act the same way.
2. The wording on tokusei rate is also pivoted around the "damage dealt" instead of affinity or power just like stat rate adjustments. I think this is safe to assume is treated the same way but as "generic" damage. The demon rate adjustment on Seth adds weight to the idea that its not just supposed to be dependency based.
3. The wording on tokusei "effect" aspects is talking explicitly about the power of the skill. To me that means it affects the calculation for the pre-rate number, not the adjustment of that number itself. It's also something that we spent a good amount of time checking for an it simply never raised on skills, only lowered from rate adjustments.
4. The drained HP from Seth in our example appeared to have been pulling the healing rate from the _target_, not the source. I can't prove this is a bug but I'm just going to assume it is as it makes no sense to me since it wasn't a reflect to an absorb even.

So to conclude the changes for this will be as follows:
1. Static/percent dmg/heal from RATE and RATE TAKEN stats as well as DAMAGE_DEALT and DAMAGE_TAKEN tokusei aspects will apply to the final calculated number for all damage formulas. Right now those just apply to the non-static/percent formulas.
2. The healing stat rates in change 1 will apply during the drain calculation, using the rate of the source of the skill, despite the original behavior during the Seth fight implying it came from the target. The number used for the basis of the drain will be the final amount dealt to the target regardless of the formula type as this is something we saw when a static damage skill was clenched.

This is what will remain unchanged:
1. Tokusei EFFECT_POWER aspects will not apply to anything but the normal damage fomrulas.
2. BOOST stats will not apply to anything but the normal damage formulas and will remain affinity capped.
