### ISSUE TITLE
Demon Partner's AI can't handle Skills like Cup of Babylon/Erosion Hex

### ISSUE THREAD

**Issue by Verreater** [comphack/comp_hack#888]
If you let a demon with skills like Cup of Babylon or Erosion Hex fight on their own and they try to cast those skills, instead of casting them as soon as the incantation is done, they will just follow the enemy and never actually use it.

https://gyazo.com/b771e21156087e2f1ee2dea5fa99f96e

**Comment by HACKfrost** [comment]
Can confirm the client AI just doesn't even try to execute after the skill is activated. If you activate it yourself, either tabbing to the demon or not, it works just fine. The common factor seems to be skills with target type "none" and valid AoE target type "enemy" as they do not exhibit this behavior with support skills that don't actually target. Given the fact that this literally only happens if the AI is driving the whole time, I'm fairly confident its a client bug but I admit its rather nasty looking. Do we happen to have any reason to believe this didn't happen on the original servers? I know people turned off their AI all the time so tracking down a video is probably not going to be easy. I don't know if I want to hold the AI's hand here because that opens the floodgates to trying to fix the client AI.

**Comment by HACKfrost** [comment]
Closing with 'wontfix' label as we can't prove how this used to work and all signs point to the client AI being crap given certain skill parameters.
