### ISSUE TITLE
Spin does not hit every enemy within range

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#924]
Tested in Community Area (270101), pos 500, 0.
Enemy "Watermelon" was placed every 100 units (positioned with pos command) from 500, 500 to 500, -500 and from 1000, 0 to 0, 0.

[Video from ReIMAGINE](https://transfer.sh/xVOpG/2019-04-22_14-25-22.mp4)
[Video from locally hosted server](https://transfer.sh/Gx8Mp/2019-04-22_14-44-50.mp4)

As you can see, the spin aoe which is supposed to hit all enemies within range skips over enemies within range very often. I'm pretty sure this isn't an issue with monsters moving (because the melons don't move) and displaying the wrong position client side, and it can't be a latency issue as the same thing happens locally.

Furthermore, it seems that the exact same melons were targeted based on which direction the player character hit first. On the first hit for both characters, the spin hit 2 melons (200 units) on the rear and each flank, and skipped the third melon in front, hitting the fourth.

**Comment by HACKfrost** [comment]
From the video, the primary target (the 4th melon) is being hit further out than the AoE range seems to be extending. SOURCE_RADIUS AoE with a target is "target plus AoE" and based on skills like skill 443 with a target range of 1000 and an AoE range of 100, the interaction between these two is likely supposed to be detached like we have it. I highly doubt simply being a spin should change that logic as despite what much of the community likes to claim, there are data points that explain nearly all skill logic outside of action type.

As for the bug itself, I'm willing to bet the hitbox size is not being factored in properly when calculating the AoE targets. Is this what is being seen every time someone talks about spin? It shouldn't be very difficult to correct and it sounded much spottier when others talked about it in the past. This looks consistent and easy to explain/correct.

**Comment by alkalime** [comment]
There is one other spin bug I've heard of but it's unrelated to this and I haven't been able to test it yet. When I do I'll make another issue.
As far as I'm aware this is the big one that most people are talking about when they talk about spin being broken.

**Comment by HACKfrost** [comment]
For transparency I am adding the effective source for the skill's hitbox size to the AoE range, much like the client does when calculating if you can hit the target of a skill. This will be added to all AoE types except TARGET_RADIUS because the target ranges seem to have no relation to AoE ranges (understandably so) and every skill of this type that I have tested that causes an explosion seems to hit what its supposed to visually. This will affect skills from players or demons including enemies so make sure people are aware if enemies seem to be hitting better too. They were not given an edge :)
