### ISSUE TITLE
Game crashing when fusing with Passion Polter Lilith

### ISSUE THREAD

**Issue by thidiangel** [comphack/comp_hack#929]
today i tried to fuse some holy beasts to dm.... im with a passion lilith to use ,
when i tried to enter double fusion screen.. my game frozes and i get a megaten stop working error

take me 5 of this  error and re logins to discovery. I guessed the only variant demon who could be doing this was Lilith.
i put her on the demon box and. the game stop crashing.

**Comment by HACKfrost** [comment]
Do you mean it crashes before you actually fuse anything? If that's the case we'll need a lot more information about that demon because very little is sent from the server before actually fusing. Is this local or on a publicly hosted server?

**Comment by jdnh2320** [comment]
It crashes as soon as you click "double fuse" from the Cathedral Master's menu if you are using the English translation. I believe this affects any of the demons given from item 9954, probably because they are variants with abnormally long names. This part of the translation is Marvelous-leftovers and I believe Verreater was looking into it because we discovered this issue a few days ago. I haven't heard of this being an issue before, so it is possible that it popping up now is due to our active translation effort.

**Comment by thidiangel** [comment]
YES , in the moment i click in ''double fusion'' the game crashes and stop
working. ONLY with this lilith varriation.  its on RE normal server not
local.using locale and stuff; translated . i cant even see the fusion
screen, it frozes on the blue guy.

Em sex, 26 de abr de 2019 às 02:01, jdnh2320 <notifications@github.com>
escreveu:

**Comment by thidiangel** [comment]
my only demon on the slots is a lamia,cerberus,unicorn, a quickly inugami,
a quickly archangel and this lilith

Em sex, 26 de abr de 2019 às 03:18, thiago felipe <thidiangel@gmail.com>
escreveu:

**Comment by thidiangel** [comment]
was right..

Em sex, 26 de abr de 2019 às 03:19, thiago felipe <thidiangel@gmail.com>
escreveu:

**Comment by Verreater** [comment]
Its proooobably because someone translated the Demon Races, making the "full" names even longer
Someone will likely end up having to change their name in the translation

**Comment by compomega** [comment]
Client crashes due to the translation are outside our purview. Please contact the translation team with your problem.

**Comment by thidiangel** [comment]
dude..... on discord says to send reports on your forum.. idk even who is
this team on RE imagine

Em sex, 26 de abr de 2019 às 09:32, Omega <notifications@github.com>
escreveu:

**Comment by compomega** [comment]
I'm sorry that the ReIMAGINE team has not been clear about this. Let me help you understand the situation. Our team has existed before ReIMAGINE existed. We have never and never will be part of the ReIMAGINE team. We provide the server software and tools you, ReIMAGINE or anyone else needs to run your own private server. What we do not provide is a translation or custom content.

In this case ReIMAGINE is doing the translation so any issue that arises from the translation should be brought to the attention of ReIMAGINE; not us. Please try their translation issue channel. In an ideal world ReIMAGINE would take your bug report and forward it to us if the problem needed to be taken care of by us. Unfortunately they appear to be unwilling to collect and triage bug reports.

**Comment by HACKfrost** [comment]
Thank you for posting the issue here as it was the correct channel to do so. To a player, a crash happened and you're not sure why which is a valid reason to investigate here. Omega's response that we don't handle translation issues was accurate when we received more information but it seems it may have been misinterpreted as us blowing it off. There is a translation issues channel on the official re:imagine discord so please relay this information there now that we know the most likely cause of the issue.

**Comment by thidiangel** [comment]
i wil try.....but allç the bugs they tell to report i on your page so... i
wil report on discord about tranlation


Em sex, 26 de abr de 2019 às 20:55, HACKfrost <notifications@github.com>
escreveu:
