### ISSUE TITLE
Peorth - Party members not showing on map

### ISSUE THREAD

**Issue by Rayerra** [comphack/comp_hack#959]
After updating to latest Peorth hotfix i noticed that i cant see my party member's on map screen
Its nothing major just reporting this bug

**Comment by HACKfrost** [comment]
A bit confused here, do you mean this display?
![party](https://user-images.githubusercontent.com/22385997/58504357-3e521400-813f-11e9-8cfe-601f3504050b.PNG)
Is this only happening to you in certain zones? I can see the white blips on the minimap too. Make sure you test with unmodified client files too if its not working at all.

**Comment by Rayerra** [comment]
yea cant see them on the minimap. I'm running vanilla Comphack il provide a screenshot:
https://www.dropbox.com/s/t3igmpcvyzb4jjb/ImagineClient%202019-05-28%2014-53-36-665.png?dl=0

**Comment by Verreater** [comment]
I have had that happen previously on random occasions, but i have never been able to reproduce it.

**Comment by compomega** [comment]
Is this intermittent? Happens all the time? Only with a translated client? Under what conditions have you observed it? For example, is it when a party member disconnects and is re-added? When they enter a zone? Return from an instance? When you do one of these things instead of your party member? Without more details we can't reproduce the issue and fix it. Please provide more detail if you can.

**Comment by Rayerra** [comment]
i restarted my server today and the bug is gone so this can be closed
