### ISSUE TITLE
Using a wrong password at login disables login entirely

### ISSUE THREAD

**Issue by fbordas** [comphack/comp_hack#969]
At login screen, attempting to log in with a wrong password disables logging in entirely, as textboxes and button will not become enabled again. Unlikely to be an issue carried over because back in Aeria/Atlus/Marvelous trying to log in and failing would allow attempting again without closing the client.

Host system specs:
Windows 10 Pro build 17763
16GB RAM
3GB VRAM (GTX1060)

To reproduce:
1. Open client
2. Attempt to log in with a wrong username/password

Observable results:
1. Textboxes become unmodifiable
2. Login button becomes disabled
3. "Remember Imagine ID" checkbox becomes unmodifiable

Expected behavior:
1. Textboxes should become editable after "wrong username/password" message
2. Login button should become usable after "wrong username/password" message
3. "Remember Imagine ID" checkbox should become usable after "wrong username/password" message

**Comment by HACKfrost** [comment]
The original servers disabled the non-web form authentication method by essentially slapping an identical login form on top of the old one. That method is not our default but when using that mode on this server, this issue does not occur (though it does have some other issues). We have no reason to believe the non-web auth method handled error codes properly when the servers shut down and it wouldn't be the first thing CAVE broke in the client over time. I'll let Omega decide how to file this issue.

**Comment by compomega** [comment]
Okay there are a few things to unpack here.

There is essentially three authentication methods:
* JP classic - This is what you see when you log into most public servers. This is the login method JP used to use before it was replaced with the web auth method. This method **used** to function as you describe.
* NA classic - This is JP classic with some internal modifications to how the authentication was done. This was probably done to accommodate the way accounts were stored in the Aeria/Atlus/Marvelous database. Aside from that it functions the same as JP classic and as you describe.
* JP web auth - This is what JP switched to over time. This presents an embedded web page you authenticate with. I'll describe how it works below.

Aeria/Atlus/Marvelous had what we refer to as the NA client. This client is essentially an older version of the JP client that was translated into English with a few other modifications. It contained the code for the game mechanics that were available in the US/NA version of the game but nothing more. It used the "NA classic" authentication method. We don't support the NA client nor the "NA classic" because this client lacks so many features players enjoy today. It doesn't make sense for us to expend additional effort to support an older client that can only function at some subset of the fully updated client.

Japan had what we refer to as the JP client. The JP client used to use the "JP classic" authentication and it was later replaced with the "JP web auth" authentication. I personally do not consider the web auth method more secure or otherwise superior to the classic method. It negotiates an SSL connection to a website for authentication. This offloads some work from the lobby but it has downsides as well. You can point it to an unsecured HTTP site. It does not validate that the site it is connecting to owns the expected SSL certificate (just that it has a valid certificate). If you were to create a transparent proxy you would see your password being sent in plain text to the web server as it is not hashed prior to transmission. Note that while this is possible it is very unlikely to happen. As a general rule you should probably not use the same password for multiple sites or services. The classic method does not have these weaknesses which is why I prefer it. The classic method also works with Wine (and variants) if you wish to play under macOS or Linux. Your guess is as good as mine as to why they switched to the web auth method.

Now that I have had my rant, the fact is the latest JP client that supports all the features players want is meant to use "JP web auth" for authentication. We have found that the "JP classic" method may be patched in the client and restored to partial functionality. When CAVE switched authentication methods it didn't fully replace the relevant code. When you use the web auth it actually places a "password" from the web server into the password box of the original UI and initiates the lobby login. This is both stupid and useful because it made it easy for us to re-enable the "JP classic" method. Finally, the problem is that when the web page fails to load or for some reason the lobby login fails after authentication, the original UI is locked to prevent attempts to login from the old UI that was left in.

What this means is that you see the undesired behavior noted above. It may be possible to patch the JP client to prevent the locking of the classic login UI. That being said, this task requires significant time and skill to perform and is a fairly low priority task. You are welcome to leave the bug report open but it will probably not be addressed anytime soon.

**Comment by fbordas** [comment]
Fair response. I totally understand not seeing any noteworthy activity on this issue in the short term, but for the sake of accuracy and quality control I think it's best to report all issues that *can* be solved, even if it means much later in the development timeline.

**Comment by compomega** [comment]
Fixed and coming soon to a server near you.
